# Generated by Django 5.2.8 on 2026-04-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('quinceanera', 'Quinceañera'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('corporate', 'Corporate Event'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('promo_opt_in', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
