# Generated by Django 5.2.8 on 2026-04-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('hero_image', 'Hero Photo (top of homepage)'), ('about_image', 'About Section Photo'), ('gallery_1', 'Gallery Photo 1'), ('gallery_2', 'Gallery Photo 2'), ('gallery_3', 'Gallery Photo 3'), ('gallery_4', 'Gallery Photo 4'), ('gallery_5', 'Gallery Photo 5'), ('gallery_6', 'Gallery Photo 6'), ('video_1', 'Video Showcase 1'), ('video_2', 'Video Showcase 2'), ('video_3', 'Video Showcase 3'), ('video_4', 'Video Showcase 4')], max_length=30, unique=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('file', models.FileField(upload_to='site_media/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, help_text='Video title or gallery caption', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Media',
                'verbose_name_plural': 'Site Media',
                'ordering': ['slot'],
            },
        ),
    ]
