# Generated by Django 5.2.8 on 2026-07-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_active_dates_test_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False, help_text='Temporary/substitute musician added from an event page; cannot log in'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('musician', 'Musician'), ('lead', 'Lead'), ('admin', 'Administrator')], default='customer', help_text='User role determines access permissions', max_length=20),
        ),
    ]
