# Generated by Django 5.2.8 on 2026-04-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('folder_name', models.CharField(max_length=200, unique=True)),
                ('genre', models.CharField(choices=[('ranchera', 'Ranchera'), ('bolero', 'Bolero'), ('son', 'Son'), ('cumbia', 'Cumbia'), ('norteña', 'Norteña'), ('huapango', 'Huapango'), ('vals', 'Vals'), ('corrido', 'Corrido'), ('pop', 'Pop'), ('other', 'Other')], default='other', max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('has_audio', models.BooleanField(default=False)),
                ('has_score', models.BooleanField(default=True)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
