# Generated by Django 5.2.8 on 2026-04-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians_portal', '0003_event_google_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('quinceanera', 'Quinceañera'), ('birthday', 'Birthday'), ('corporate', 'Corporate'), ('church', 'Church'), ('festival', 'Festival'), ('private', 'Private Party'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('musicians_count', models.PositiveSmallIntegerField(default=1, help_text='Number of musicians at this gig')),
                ('rate_per_hour', models.DecimalField(blank=True, decimal_places=2, help_text='Rate charged per hour (total, not per musician)', max_digits=8, null=True)),
                ('total_charged', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount charged to client', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gig',
                'verbose_name_plural': 'Gigs',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
