# Generated by Django 5.2.8 on 2026-07-12 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians_portal', '0009_add_is_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Gig Contract', max_length=100)),
                ('terms_en', models.TextField(help_text='English contract terms')),
                ('terms_es', models.TextField(help_text='Spanish contract terms')),
                ('is_active', models.BooleanField(default=True, help_text='The active template used for new contracts')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='gig',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='gig',
            name='client_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('gig', 'Gig'), ('rehearsal', 'Rehearsal'), ('absence', 'Absence'), ('other', 'Other')], default='gig', max_length=20),
        ),
        migrations.AlterField(
            model_name='musicianpay',
            name='musician',
            field=models.ForeignKey(limit_choices_to={'role__in': ['musician', 'lead', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='pay_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('event_type_label', models.CharField(blank=True, max_length=50)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overtime_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Overtime rate per hour', max_digits=8, null=True)),
                ('terms_en', models.TextField()),
                ('terms_es', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='es', help_text='Default language shown to the client', max_length=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('signed', 'Signed'), ('voided', 'Voided')], default='draft', max_length=10)),
                ('sent_via', models.CharField(blank=True, choices=[('sms', 'SMS composer'), ('email', 'Email'), ('twilio', 'Twilio SMS'), ('link', 'Link copied')], max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('signed_name', models.CharField(blank=True, max_length=200)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signed_user_agent', models.CharField(blank=True, max_length=500)),
                ('signed_language', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='musicians_portal.event')),
                ('gig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='musicians_portal.gig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
